### ISSUE TITLE
MDX is unable to utilize Playwright following its update

### ISSUE THREAD

**Issue by torn4dom4n** [stereobooster/astro-digital-garden#5]
Hi @stereobooster, thank your for instructions about use mermaids in markdown.

I'm not sure this issue is a bug of @astrojs/mdx or playwright but MDX is unable to utilize Playwright following its update. This is [full log](https://github.com/AREA44/playastro/actions/runs/9068425188/job/24959798627) of GitHub Actions after I update playwright from 1.43.1 to 1.44.0. I tried a few solution but nothing is work. Could you provide me with a solution for this?

**Comment by stereobooster** [comment]
Try to retriger action without cache. I see same issue with Netlify. This is general playwright issue in CI-like environments

**Comment by stereobooster** [comment]
You may also need to run `playwright install chromium` in CI (at least this is [what playwright recommends](https://playwright.dev/docs/ci))

```yaml
      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium
```

This is what I do https://github.com/stereobooster/beoe/blob/main/.github/workflows/ci.yml

**Comment by stereobooster** [comment]
For me everything works. This is general `playwright` issue. You can try to ask in their repository - maybe they have Github discussions or Discord
